### ISSUE TITLE
Return cropped image nil

### ISSUE THREAD

**Issue by lxdyglt** [brynbodayle/BABCropperView#21] opened 2017-03-19 02:37 UTC
Same as issue #11

It looks like for image I took from camera it doesn't work.

A not working image always not work (but if I use the iOS default editing tool do some edit and save, then it works).

Images from screenshot or from other sources always work.

Attached is a couple of not working samples FYI (same image works on Emulator but not on real device)

**Comment by lxdyglt** [comment] 2017-03-19 02:41
Please make an urgent update of this if possible.

**Comment by brynbodayle** [comment] 2017-03-19 03:15
I wasn't able to reproduce this issue using the images you provided. How are you testing this? On a particular device using the sample project?

**Comment by lxdyglt** [comment] 2017-03-19 03:53
I did it on my on project with your library which is xcode 8.2.1 with Swift 3.

I can only run your sample project in an emulator (not sure how to avoid code signing issue to test in device).

**Comment by lxdyglt** [comment] 2017-03-19 04:06
With the dud image and debugging into your code, I found that the following line calculated "bitmap" was "0x0" which is abnormal:

`CGContextRef bitmap = CGBitmapContextCreate(NULL, scaleSize.width, scaleSize.height, 8, scaleSize.width * 4, colorspace, kCGImageAlphaPremultipliedLast | kCGBitmapByteOrder32Big);`

This is from your "BABCropperViewCroppedAndScaledImageWithCropRect" method in "BABCropperView.m"

**Comment by lxdyglt** [comment] 2017-03-19 04:42
A further discovery from debugging the above code: for the same image was taken from the camera (dud one) and then copied out and into device (working one):

the value of "scaleSize.width" & "scaleSize.height" from your code swopped places. Apparently when the image was taken from camera and loaded in to your BABCropperView, the width and height somehow switched place.

**Comment by lxdyglt** [comment] 2017-03-19 05:23
This bug occurs whenever the image orientation is not up (when image taken from camera the default orientation is right).

Can you fix it?

**Comment by brynbodayle** [comment] 2017-03-19 17:02
I've tested with these two images `Landscape_6.jpg` and `Portrait_6.jpg` and couldn't reproduce. They are from an image set which contains all the possible image orientations and are themselves image with the RIGHT orientation.

What orientation is the image you are testing with? Could you perhaps zip it and send it to me? I think GitHub will normalize the image rotation on upload.

[exif-orientation-examples-master.zip](https://github.com/brynbodayle/BABCropperView/files/853381/exif-orientation-examples-master.zip)

**Comment by lxdyglt** [comment] 2017-03-20 00:31
It seems whenever I copy the image out it works.

If you don't mind leave your email here I can directly sent you the original image through mobile email.

**Comment by brynbodayle** [comment] 2017-03-20 03:00
bryn.bodayle@icloud.com

**Comment by lxdyglt** [comment] 2017-03-20 04:24
Email sent

**Comment by jayjayesh** [comment] 2017-09-19 12:26
i'm also, facing this issue, i have placed this library in landscape viewController, when i select image then get croppedImage is nill.

**Comment by brynbodayle** [comment] 2018-02-24 17:44
Please try again with version 0.5.2, I believe this issue should be fixed now.

**Closed** 2018-02-24 17:45 UTC
